apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgAS24g+cuQRpnWP4V9UWv6YacX4I+/DJwoSoGYMC0ys6tnWtOd6eyREezdHkr3zn8kZso5pTG1fkNO7r/QiUMDwo5CXYA7X9/yBz0X6tAwiNRb7MTD2MLJOHuY04cpT7IAU5SUvwOqLCBDcSruN1yUD1qGWvjI0fx8e/37QJ47uWAiCcObfL8CNFAnZy7Fme2f8z2oGidDcuJEONTwDS2nhT7D3slL99nxPVhwqlGj2mXImaSZHoTHbZ2eO5pEcqvknp0OT6KHCZcoAcfxM6L4OZ9/zJidTriY8O1FMEPGvRAFaBAZtiZQGttplOThHYgjF60uViM5GqqWCc1b7HEw0cDDT8FFf1tJ0e5cUWUR8CkUxe6D3kId8GBWS/4f/BVrNWRHigWOIbdNN/zl0mJrbivpvS0nxUVVrA1mbhf+tQQ218x/MCVNpVRorDJvnoBgUtN3uXt5i9Fs6hr13l5S7wZafM1B7evVjG7bvWaxAhMWgL4i+5gGLTAGOC1/75lUycK8yf/QruJbMfU19KDSoOW6r86r7V6C67dNQTiVSzAqMT64xsU/FlFtzwUHIbrAF+U02/QZVUGHIfnJiNtFM6AXy0NcombQyRKGoUhUFb81XYed9CGdN4DsoOsWrybv0pTqX039zGYX8K0g5p1upOKJQ5GqG9NV2LTMy8ONzInuLKOwT9N41s0ffI6XdfSdeuDQj0LtycsVc8fkkGi89+KklIhkTurZh6pNbCXkM6w==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
