apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgCrHLA+jnYRIGxaDRdLVc5X1yb5Vwz3jkaYDwxGFdzP4xBDwCqo4G+XTFUb/kaqSx+coIyclRjA4/fbFYUo45Fe8YIAwWualhtivY7hsrq/ut34AKdqJEjVX33FVl6J8thEZSBYFQyIBnvhez7vuY9CtLmYrnzN1X6Eqajzl6nYdCap9DcKPgO2hbzwVglNffKgwt+Ij3CZl9wsBMYwmKTZXAAFhwXwOJnt3dLjz2GGdT1VaAgW73s0ue/CnZhVuOJLjLl1S6giewu1vSnElid0YJVTmLap5tL2G+ml6lgHjVOCM1H/t5YoYBblNk3MERz9ZLYgabOoIt1QcZJqpaekAKeNikOqaHtw7cnATTGhonOrHGYR98oo2XOFql7CrDh2Io99yVL5m5PnK/Z6o/KkW2ioudSeA+xn1ZUCGFYEyjdO7P9Jxr198k//FwJca+FnogFaZh/fcVF+SxA21CNcK/1uBW8j75hyPtwbAAkNSRaISeQQcP2hZg7fN2kuBJI55nn81VLM5RGvrv/MF/6obUEVYtdKSoY1NRhxE81dCIbHll2+63Pe00rbfT6QGgZ2SCnBazdJXfHyb2N6ehnsKqkyy9MTMV9k0gid+Hou3GMbxRGUmo22r48sTTQFvgQG1bnBMbFhMFXbBm0r8Fbj6GdRl32xshAwDxmv9vPv+ljVwdXT0xqcQwApoeXrixDw3mDn3OVMh0Vn9FRj40GEYE2mK3tV8Zgov8EhC4+ang==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
