---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-josephine-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    JOSEPHINE_API_TOKEN: AgDEuEtdDafMQneu1vZ4OgJZyf9FjUdFGYZyeXh8l+N8rpFKtV8bJoMVMzSghli5KL81k0ayP1N0qGoLq1NtgldGUn7NKGYFSpJUGwgsiilmtqBWfTM0eMAlkffozvRO72wjhtV8vT9TCtUtxPDEicE3RI+gA0WItGzqix9WRd8guc4rEtt7rxJnB5jHS22SBVl0KV0HksJStpqLyZp98v2D5nMfTDqC3Ngbogn9u6q8+NefZXG19PxJgqOLESTViAxJZND9MmucRugMNrS1f50EEIEFN+d4lqArGI7O/0TnWCLLQkgG7paN+gH2xuBla4oxI5nxF4TbgZo7Q4WiWlgvpNQlMSkLUctjlMgupM5Prbq4h+8HSSPBT6mew5Sp0HRivg0ZNd6g7dmgtJ30od8zzAFUYJxnAvLMhmS7WYBCYEtNyXni1bVBu5n8c9254GMCFDjLV2w3M8HTHh26Z7Fk5L0K6qXLfP8qvn3hv6Z9U7s2+oANWFIYq6UFUoTr8sE2FypDBqP2vRyDEiO67CwNOcwq3XNTB1oGwhBStAO0pIMTfV6uk/jspXrRoIo6oF990ebRQ5ZzVXbEnXUek8FZWwESRtws2KSK47t2cifvfn/rNXK2GUE1iIR1wHJVcNDyMMj6bU0+b2iFxaEdjK7NG3OoDRyVW2HSatO9V2MeiGCy5Rt38Czr9lLc+UUgG0qNNX7PWQVZ+Hq9p8ObQG0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-josephine-secret
      namespace: ${NAMESPACE}
    type: Opaque
