apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-nalgoo-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    NEXT_PUBLIC_NALGOO_API_KEY: AgBY26yWUrr31eSqwebMoi5sowyqeMYu+Qp8R3g4TJMdiClK+3GbHAZx7DXe65b8yO6ASoe6mxzl/yFMV28n74bAr+nvQBj05B0sIVwaiWHXbrIBe4TWZdGnPzSXFpJPwagjdGrkXI+dlsHRYx6gDll8TJ4csIgC0MEVq42q8Px4PEVWhqbdqG4DfI7HWuuNzZW9XmaCsCSvgeIYDnbM0Apk1toB9JFBkjLsNohX0lrkpdf1V+ElwcT6MEeSGSF5jlXyHTx7Nfc7hG/6GbWQpnizJ/20BhMTCG9AeOMXvuPGVr+fMipcgv8lTQmhPOLDhAgy+ogCLD60grHhQBM7Rug7/3MmZHD0hGLRFdb1Hl8oJ+Wqh5Zf9j9fMk6n6UTcZ+YHboTWlNp7fyqWPms3CM1n26e8RPy1Fip7JXconE7LTK0+05ehTuvvSnOSoHRtJp3Vm52gSuzYHNZ4WVQlNlxSJ90uOgcg0zeinsibo79QA2w/kHcySJttiBC5abkyclgv9n8yPr2l85Dy1qE3sSYk9De2PIxRFy1zN1HKC554K7WFDObrmYVPXZPXLSV7GKDv12pgcEL7Xzv1iZaRawEhYtDzL5EEahZdzGo6M+1dQMCOE2ZRNCsleqxeeSU65eOd3WGxCEaDrlDjRVtdyUItbkRjz21Bd2ohgj8AW59pKluT0ftgeEvPxLxspc+M65YmRTPat7H9sJMbzcWfhYR3o/+DX/KZ4nWejeAXR4UVdQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-nalgoo-secret
      namespace: ${NAMESPACE}
