apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: olo-next-revalidate-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgCWd9CTzTMcscH8xINkDWTDInzgv/FrHFO1NXAxvjzRTZEdUueImzw9vyuPwa+kUMKSSTjkdvxtXKYY7PNL4zUlphidpd1nx9vMwhy8a8WL949+94pNnGF6pBxfUqxCp28PZp6yTiYA1eoNWBVM4j3vpxMdNzT6t10wjnUw6OkutuQ+cmZyk+5gHEre9VKPJyTq8QjU0oS0i1b9I8C+hapF4DeY8YfZadTFC+TSEnR2ffaLu/3JTTzDJqOJ4ERgQcsKGdLuMqRdCokYcyLmGVfaVeNcnOUrtJO9k7+ZErnPyA08n4J+eD8y1Dj1mgL+L5PgDmCUQuxN3eNb6o+598++B09KbW1ViBV7jBoCas6VVUdsESk9BM2mm3Jam4veLpR6Gs3bUzL+QtJ82BZXuMvFDGqCZQMuCPIg/B4taPhOTI37Xgv+CtXh2zZzFloZfIIW8K6uhKHwQI8cXwLzMi2vB14uIjPThDMRSvtzdosaQQHvC4sktXbg8mSXpcS5uQD52+hWHgqw8GozRqUFVF8um8v+g4N79Td64zw2y+H3ji89NmpVZKi6oOdWK4f/ARQ6ev0LGjvp5pO6GO7j7/cSBHdu52vHN2dolOtMzPuNgBM2C9zz2YmE0c1mH86invQ9EaLxmbyPUhTtyJcIl/sHOqQUviKaLHJDzXguW5DGXODxJbXKzviOeUV4CX+j7hodnUcWg9VVGM0Bgt+OUgZid67Mx6niEuuQ9P7+BO0CFA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: olo-next-revalidate-secret
      namespace: standalone
