apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgBJdgecrpAVi6YNxhGvu26Z84moRdovjRZ0rInOfkOUbpXDvHIr+e7mdPjDyFQsW7zWwN3y3zfj/KN7qI0aDDT66+ZPHKed4ZCxRk6aPG8Aud1Z2SssHmbF9fResOuNJLPXyOVqgv2GwOC/HtZmVhO8wN7rUQFDWOMYBDp38dihZB9Ry6a2CoFOShA4ZIoCKmZ9Ua9U+iuBptmgMBEpIKE1RjQeXckS1zKOKYOY1wTu+giu0DxeghvnZ06WIpAamBXgUDwoYra4Es+2SoQxyt2wCvzBu5M0xruVPgVAHC87DO5lYcVblb9QFIl9RtTl76iN3gvPGriMAqv+11I5UPee+eyxK+MwUQS1bsBv6sORdnhdamORFi6zniSrdnmDS/duVDjvpELbO5sIz9EDguj9qkyRrS6RoWT/ojuKFnqpz2ChsqvWs3hCP35z/Eas5XTmrkF3tLlEkW0EaIyTwN4ye9+DObVoRJNKWf5ESniBvH3uvHhyzKLcU6TIj94061AKlDST146bzdy6lA1EMpGKH6iv2qWLnaI7bOF2Rr73v+8dzrZB17DewlT265RI90lnAHLmsELsK2gu2coJyrdCEUDUxMdmOZvJvWNof83VgTljnbeeP92O4yzXGrM6mI5hQ+os2EE5zwrJZWL9TZa0am8Pre+x38JIz8fHRy8acB0TtefPHlX2YnGnkl7H6UBW/OeurFh37PTykQYg6/IJpmdm4djvc5J5QE/zPXwzGw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
