/* tslint:disable */
/* eslint-disable */
/**
 * ATS API (Nalgoo)
 * Import and export REST API for Nalgoo\'s ATS
 *
 * The version of the OpenAPI document: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

