apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-nalgoo-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    NEXT_PUBLIC_NALGOO_API_KEY: AgBAcTzpecdJqKJTRw4N+N6XjUxU9z6oAG8bVpRK5qTOg12jFqThg6oaq4fSfgy6PkjSgfW4unCP8KqksFvmjOnxs0BBPdZX18bNXk0phiNv+tJiJz+1iJGAKWYmn21nMT+H6j3e9fXRPiIGknBMGccWgA70YEP2tgkEFCFxIIrPicK3Y+XWhtJQ2tTkxPqu2QrrAKtGItl3d6hSLnGJaLfLq7OVO8dbLIQJOmmhwEhPzMzaaLGUxI9NFf4+jCkHtVXgcoTIbYtO55bSezOd+a7+baUQyYcDwtZRaxwu+/T5YV1fQQqHk+g0/BFspYZn/+oCm/E7B93VmQ1KhK+q7O6yKgnQlMklSn2295XFKyWclNeUcIOT9sZQ20UTZj2Bj1qzT2RDS3G2clnY+ElW3D0W8GJ1gTH+/jeP+ORfobJdx/aRmwuzVT5uRAjQ2l8EkrbREeDebjeY+Tp/GflIHzdysC7f7Qqyt6kEpUw4qgXBrj6L4wHRt0jKSE3uN32muJbR2DEppVtrDDaapW62u485N0banPudV9jluigy9l8/195BoSK0o7ChTkvISaTBphCx0Ef0JT3db0ZbX0Z13cC3DY4iFkWVgRZwDfNM92xclUc71jlEwYnMOcrEnPFpxf5rkHVdfPLY+c9jClLLEjAz2kDDehfjw4qga11EO/fBXK2ew5u3rL4B/xBbvRP7F4GCZF/RtndFBIrttpWWnfoZOR0luzUDl06PLJqjfnUd1Q==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-nalgoo-secret
      namespace: ${NAMESPACE}
