apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgAmD216i/pJR0E/khSFJ+pg0s6ULI7RiUF/ssPLIL4niV5Rjuek9i4B5AsNrsIHzDDBmWexrxJ17uBL9EIM8kju/uQu2u/sKN8iZFaJiyKWw/FXxPbP7/85wK5JmTyuMaJLvvpMAieXKW4fS4A5crGVHc7b+thkxhXPcisDWI0Z97XTJeoRu+QvBhlInPRQ+Qn1pVrhs2EdgYLFu8GqtVQvqSEU9u88t3osaSuMuyufNVIcvm2eldXSVv8N6MXvvyPkUcVumvd0k9NSaNC6nfvIOycVQehhTxal/FrjbEZ22sSgbDwQE6iErvHY0vYrIxiLYu5dtq/qGO5oOYYyBciXZjQL/qroNnM+iLtlCbOSKABQ6Be0o+WG/8GCyLDcBhRzrVz3IVZSm0aXLdVON1/0scKZYIwwpbbjnCQ8HLA9n6UNSTTtbAgZUWsx+gtIpgFn/pmbY4GMTftAG+YeI98W9BzMVN+gpN47WW8KUXvrlvYCC6xGZpikHpHpLximx8amCUQJ29cs8Ld6cY9P9tj6KJCYL+rdwf7o7I7Q/RGeRBACTbcFfjTNfCIIAn56Kdfv1ghnFgPfxJ5xxak3rcCsElzpy7zGipnE0RV8bx6D2UffdHM70uD07AkzumYnXx0h29eHLNVaKnzpc8uKDPwEjwGipp7hrgc9HWRApZdtA2+8PIjw9VVhvy40hMsFs1Dy0DEoPC3x6XqB47FSK1YqtEBSrWL5uGjlaa1XNCBj2A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
