fragment Link on ComponentItemsLink {
  label
  url
  page {
    data {
      ...PageSlugEntity
    }
  }
  article {
    data {
      ...ArticleSlugEntity
    }
  }
  branch {
    data {
      __typename
      attributes {
        title
        slug
      }
    }
  }
  document {
    data {
      __typename
      attributes {
        title
        slug
      }
    }
  }
}

fragment Anchor on ComponentItemsAnchor {
  label
  targetId
}

fragment UploadImageSrcEntity on UploadFileEntity {
  id
  attributes {
    url
  }
}

fragment UploadImageEntity on UploadFileEntity {
  id
  attributes {
    url
    width
    height
    caption
    alternativeText
    name
  }
}

fragment UploadFileEntity on UploadFileEntity {
  id
  attributes {
    url
    name
    ext
    size
    createdAt
    updatedAt
  }
}

fragment FileItem on ComponentItemsFileItem {
  title
  media {
    data {
      ...UploadFileEntity
    }
  }
}
