fragment Link on ComponentItemsLink {
  label
  url
  page {
    data {
      attributes {
        slug
      }
    }
  }
  article {
    data {
      attributes {
        slug
      }
    }
  }
  branch {
    data {
      attributes {
        slug
      }
    }
  }
  document {
    data {
      attributes {
        slug
      }
    }
  }
}

fragment UploadImageSrcEntity on UploadFileEntity {
  id
  attributes {
    url
  }
}

fragment UploadImageEntity on UploadFileEntity {
  id
  attributes {
    url
    width
    height
    caption
    alternativeText
    name
  }
}

fragment UploadFileEntity on UploadFileEntity {
  id
  attributes {
    url
    name
    ext
    size
    createdAt
    updatedAt
  }
}
