fragment RouterEntity on RouterEntity {
  attributes {
    articlesParentPage {
      data {
        ...PageSlugEntity
        ...PageParentPages
      }
    }
  }
}

query General {
  router {
    data {
      ...RouterEntity
    }
  }
}
