fragment ImageHeaderSection on ComponentHeaderSectionsImage {
  media {
    data {
      ...UploadImageEntity
    }
  }
}

fragment SideImageHeaderSection on ComponentHeaderSectionsSideImage {
  media {
    data {
      ...UploadImageEntity
    }
  }
}

fragment GalleryHeaderSection on ComponentHeaderSectionsGallery {
  medias(pagination: { limit: -1 }) {
    data {
      ...UploadImageEntity
    }
  }
}

fragment BranchMapHeaderSection on ComponentHeaderSectionsBranchMap {
  branches(pagination: { limit: -1 }) {
    data {
      id
      # TODO fragment
    }
  }
}

fragment FeaturedNewsHeaderSection on ComponentHeaderSectionsFeaturedNews {
  articlesTitle
  firstArticle {
    data {
      ...ArticleCardEntity
    }
  }
  secondArticle {
    data {
      ...ArticleCardEntity
    }
  }
}

fragment IconHeaderSection on ComponentHeaderSectionsIcon {
  iconName
}

fragment PickupDayHeaderSection on ComponentHeaderSectionsPickupDay {
  carouselTitle
  anchors {
    ...Anchor
  }
}

fragment HeaderSections on PageHeaderDynamicZone {
  __typename

  ... on ComponentHeaderSectionsImage {
    ...ImageHeaderSection
  }

  ... on ComponentHeaderSectionsSideImage {
    ...SideImageHeaderSection
  }

  ... on ComponentHeaderSectionsFeaturedNews {
    ...FeaturedNewsHeaderSection
  }

  ... on ComponentHeaderSectionsGallery {
    ...GalleryHeaderSection
  }

  ... on ComponentHeaderSectionsIcon {
    ...IconHeaderSection
  }

  ... on ComponentHeaderSectionsPickupDay {
    ...PickupDayHeaderSection
  }
}
