fragment ImageHeaderSection on ComponentHeaderSectionsImage {
  media {
    data {
      ...UploadImageEntity
    }
  }
}

fragment GalleryHeaderSection on ComponentHeaderSectionsGallery {
  medias(pagination: { limit: -1 }) {
    data {
      ...UploadImageEntity
    }
  }
}

fragment BranchMapHeaderSection on ComponentHeaderSectionsBranchMap {
  branches(pagination: { limit: -1 }) {
    data {
      id
      # TODO fragment
    }
  }
}

fragment BasicHeaderSection on ComponentHeaderSectionsBasic {
  title
  text
}

fragment ArticlesHeaderSection on ComponentHeaderSectionsArticles {
  title
  text
  articlesTitle
  firstArticle {
    data {
      ...ArticleCardEntity
    }
  }
  secondArticle {
    data {
      ...ArticleCardEntity
    }
  }
}

fragment HeaderSections on PageHeaderDynamicZone {
  __typename

  ... on ComponentHeaderSectionsBasic {
    ...BasicHeaderSection
  }

  ... on ComponentHeaderSectionsArticles {
    ...ArticlesHeaderSection
  }
}
