fragment IconTitleDescriptionItem on ComponentItemsIconTitleDesc {
  title
  description
  icon {
    data {
      attributes {
        url
        width
        height
        name
      }
    }
  }
}
