fragment RichtextSection on ComponentSectionsRichtext {
  content
}

fragment OrderedCardsSection on ComponentSectionsOrderedCards {
  title
  cards {
    title
    text
  }
}

fragment PageSections on PageSectionsDynamicZone {
  __typename

  ... on ComponentSectionsRichtext {
    ...RichtextSection
  }

  ... on ComponentSectionsOrderedCards {
    ...OrderedCardsSection
  }
}
