fragment RichtextSection on ComponentSectionsRichtext {
  content
}

fragment OrderedCardsSection on ComponentSectionsOrderedCards {
  title
  cards {
    title
    text
  }
}

fragment ImageAndTextSection on ComponentSectionsImageAndText {
  title
  text
  imagePositionImageAndText: imagePosition
  backgroundColorImageAndText: backgroundColor
  image {
    data {
      ...UploadImageEntity
    }
  }
  primaryButton {
    ...Link
  }
  secondaryButton {
    ...Link
  }
}

fragment ColumnsSection on ComponentSectionsColumns {
  title
  text
  backgroundColor
  items {
    itemTitle: title
    text
    image {
      data {
        ...UploadImageEntity
      }
    }
  }
}

fragment ImageAndTextOverlappedSection on ComponentSectionsImageAndTextOverlapped {
  title
  text
  imagePositionImageAndTextOverlapped: imagePosition
  backgroundColorImageAndTextOverlapped: backgroundColor
  image {
    data {
      ...UploadImageEntity
    }
  }
  link {
    ...Link
  }
}

fragment BranchesSection on ComponentSectionsBranches {
  title
  text
  showAll
  branches {
    data {
      ...BranchEntity
    }
  }
}

fragment WorkshopsSection on ComponentSectionsWorkshops {
  title
  text
  showAll
  workshops {
    data {
      ...WorkshopEntity
    }
  }
}

fragment PageSections on PageSectionsDynamicZone {
  __typename

  ... on ComponentSectionsRichtext {
    ...RichtextSection
  }

  ... on ComponentSectionsOrderedCards {
    ...OrderedCardsSection
  }

  ... on ComponentSectionsImageAndText {
    ...ImageAndTextSection
  }

  ... on ComponentSectionsColumns {
    ...ColumnsSection
  }

  ... on ComponentSectionsImageAndTextOverlapped {
    ...ImageAndTextOverlappedSection
  }

  ... on ComponentSectionsBranches {
    ...BranchesSection
  }

  ... on ComponentSectionsWorkshops {
    ...WorkshopsSection
  }
}
