fragment RichtextSection on ComponentSectionsRichtext {
  content
  backgroundColorRichtext: backgroundColor
}

fragment OrderedCardsSection on ComponentSectionsOrderedCards {
  title
  variantOrderedCards: variant
  cards {
    title
    text
    iconName
  }
}

fragment ImageAndTextSection on ComponentSectionsImageAndText {
  title
  text
  imagePositionImageAndText: imagePosition
  backgroundColorImageAndText: backgroundColor
  image {
    data {
      ...UploadImageEntity
    }
  }
  primaryButton {
    ...Link
  }
  secondaryButton {
    ...Link
  }
}

fragment ColumnsSection on ComponentSectionsColumns {
  title
  text
  backgroundColorColumns: backgroundColor
  items {
    itemTitle: title
    text
    image {
      data {
        ...UploadImageEntity
      }
    }
  }
}

fragment ImageAndTextOverlappedSection on ComponentSectionsImageAndTextOverlapped {
  title
  text
  imagePositionImageAndTextOverlapped: imagePosition
  backgroundColorImageAndTextOverlapped: backgroundColor
  image {
    data {
      ...UploadImageEntity
    }
  }
  link {
    ...Link
  }
}

fragment BranchesSection on ComponentSectionsBranches {
  title
  text
  showAll
  branches {
    data {
      ...BranchEntity
    }
  }
}

fragment WorkshopsSection on ComponentSectionsWorkshops {
  title
  text
  showAll
  workshops {
    data {
      ...WorkshopSlugEntity
    }
  }
}

fragment ColumnsListSection on ComponentSectionsColumnsList {
  title
  backgroundColorColumnList: backgroundColor
  leftColumn {
    icon {
      data {
        ...UploadImageEntity
      }
    }
    content
  }
  rightColumn {
    icon {
      data {
        ...UploadImageEntity
      }
    }
    content
  }
}

fragment TableSection on ComponentSectionsTable {
  title
  text
  anchorId
}

fragment FaqSection on ComponentSectionsFaq {
  title
  backgroundColorFaq: backgroundColor
  showMoreLink {
    ...Link
  }
  faqs {
    data {
      ...FaqEntity
    }
  }
}

fragment FilesSection on ComponentSectionsFiles {
  title
  files {
    ...FileItem
  }
}

fragment BannerSection on ComponentSectionsBanner {
  title
  text
  variant
  image {
    data {
      ...UploadImageEntity
    }
  }
  primaryButtonLink {
    ...Link
  }
  secondaryButtonLink {
    ...Link
  }
}

fragment DividerSection on ComponentSectionsDivider {
  backgroundColorDivider: backgroundColor
}

fragment CardsListSection on ComponentSectionsCardsList {
  title
  text
  cardsCardsList: cards {
    title
    link {
      ...Link
    }
  }
}

fragment FaqCategoriesSection on ComponentSectionsFaqCategories {
  titleFaqCategories: title
  text
  showAll
  faqCategories {
    data {
      ...FaqCategorySlugEntity
    }
  }
}

fragment PageSections on PageSectionsDynamicZone {
  __typename

  ... on ComponentSectionsRichtext {
    ...RichtextSection
  }

  ... on ComponentSectionsOrderedCards {
    ...OrderedCardsSection
  }

  ... on ComponentSectionsImageAndText {
    ...ImageAndTextSection
  }

  ... on ComponentSectionsColumns {
    ...ColumnsSection
  }

  ... on ComponentSectionsImageAndTextOverlapped {
    ...ImageAndTextOverlappedSection
  }

  ... on ComponentSectionsBranches {
    ...BranchesSection
  }

  ... on ComponentSectionsWorkshops {
    ...WorkshopsSection
  }

  ... on ComponentSectionsColumnsList {
    ...ColumnsListSection
  }

  ... on ComponentSectionsTable {
    ...TableSection
  }

  ... on ComponentSectionsFaq {
    ...FaqSection
  }

  ... on ComponentSectionsFiles {
    ...FilesSection
  }

  ... on ComponentSectionsBanner {
    ...BannerSection
  }

  ... on ComponentSectionsDivider {
    ...DividerSection
  }

  ... on ComponentSectionsCardsList {
    ...CardsListSection
  }

  ... on ComponentSectionsFaqCategories {
    ...FaqCategoriesSection
  }
}
