fragment ArticleSlugEntity on ArticleEntity {
  __typename
  id
  attributes {
    slug
    title
  }
}

fragment ArticleCardEntity on ArticleEntity {
  ...ArticleSlugEntity
  attributes {
    perex
    coverMedia {
      data {
        ...UploadImageEntity
      }
    }
    addedAt
    category {
      data {
        ...CategoryEntity
      }
    }
  }
}

fragment ArticleEntity on ArticleEntity {
  ...ArticleCardEntity
  attributes {
    content
  }
}

query Articles {
  articles {
    data {
      ...ArticleEntity
    }
  }
}

query ArticleBySlug($slug: String!) {
  articles(filters: { slug: { eq: $slug } }) {
    data {
      ...ArticleEntity
    }
  }
}

query LatestArticles($limit: Int!) {
  articles(sort: "publishedAt:desc", pagination: { limit: $limit }) {
    data {
      ...ArticleEntity
    }
  }
}
