fragment ArticleSlugEntity on ArticleEntity {
  id
  attributes {
    slug
  }
}

fragment ArticleCardEntity on ArticleEntity {
  ...ArticleSlugEntity
  attributes {
    title
    perex
    coverMedia {
      data {
        ...UploadImageEntity
      }
    }
    addedAt
    category {
      data {
        ...CategoryEntity
      }
    }
  }
}

fragment ArticleEntity on ArticleEntity {
  ...ArticleCardEntity
  attributes {
    blocks
  }
}

query Articles {
  articles {
    data {
      ...ArticleEntity
    }
  }
}

query ArticleBySlug($slug: String!) {
  articles(filters: { slug: { eq: $slug } }) {
    data {
      ...ArticleEntity
    }
  }
}
