fragment ArticleSlugEntity on ArticleEntity {
  __typename
  id
  attributes {
    slug
    title
  }
}

fragment ArticleCardEntity on ArticleEntity {
  ...ArticleSlugEntity
  attributes {
    perex
    coverMedia {
      data {
        ...UploadImageEntity
      }
    }
    addedAt
    articleCategory {
      data {
        ...ArticleCategoryEntity
      }
    }
    tags {
      data {
        ...TagEntity
      }
    }
  }
}

fragment ArticleEntity on ArticleEntity {
  ...ArticleCardEntity
  attributes {
    content
  }
}

query Articles {
  articles {
    data {
      ...ArticleEntity
    }
  }
}

query ArticleBySlug($slug: String!, $locale: I18NLocaleCode!) {
  articles(filters: { slug: { eq: $slug } }, locale: $locale) {
    data {
      ...ArticleEntity
    }
  }
}

query LatestArticles($limit: Int!, $locale: I18NLocaleCode!) {
  articles(sort: "addedAt:desc", pagination: { limit: $limit }, locale: $locale) {
    data {
      ...ArticleEntity
    }
  }
}

query SearchArticles($search: String!, $page: Int!, $pageSize: Int!, $locale: I18NLocaleCode!) {
  articles(
    filters: { title: { containsi: $search } }
    sort: "addedAt:desc"
    pagination: { page: $page, pageSize: $pageSize }
    locale: $locale
  ) {
    meta {
      pagination {
        total
      }
    }
    data {
      ...ArticleCardEntity
    }
  }
}
