fragment BranchSlugEntity on BranchEntity {
  __typename
  id
  attributes {
    title
    page {
      data {
        ...PageSlugEntity
      }
    }
  }
}

fragment BranchEntity on BranchEntity {
  ...BranchSlugEntity
  attributes {
    page {
      data {
        ...PageSlugEntity
      }
    }
    openingTimes {
      data {
        ...OpeningTimeEntity
      }
    }
    contacts {
      data {
        ...ContactEntity
      }
    }
    latitude
    longitude
    address
    navigateToLink
    mapIconName
    publicTransportInfo
    parkingInfo
    barrierFreeInfo
  }
}

query Branches($locale: I18NLocaleCode!) {
  branches(locale: $locale) {
    data {
      ...BranchEntity
    }
  }
}
