fragment BranchEntity on BranchEntity {
  id
  attributes {
    title
    address
    slug
  }
}

query Branches($locale: I18NLocaleCode!) {
  branches(locale: $locale) {
    data {
      ...BranchEntity
    }
  }
}

query BranchBySlug($slug: String!, $locale: I18NLocaleCode!) {
  branches(filters: { slug: { eq: $slug } }, locale: $locale) {
    data {
      ...BranchEntity
    }
  }
}
