fragment CategoryEntity on CategoryEntity {
  id
  attributes {
    title
    slug
  }
}

query Categories($locale: I18NLocaleCode!) {
  categories(locale: $locale) {
    data {
      ...CategoryEntity
    }
  }
}

query CategoryBySlug($slug: String!, $locale: I18NLocaleCode!) {
  categories(filters: { slug: { eq: $slug } }, locale: $locale) {
    data {
      ...CategoryEntity
    }
  }
}
