fragment ContactEntity on ContactEntity {
  id
  attributes {
    label
    text
    image {
      data {
        ...UploadImageEntity
      }
    }
    link {
      ...Link
    }
  }
}

query Contacts {
  contacts {
    data {
      ...ContactEntity
    }
  }
}
