fragment DocumentEntity on DocumentEntity {
  id
  attributes {
    title
    slug
    documentCategory {
      data {
        ...DocumentCategoryEntity
      }
    }
    files {
      data {
        ...UploadFileEntity
      }
    }
  }
}

query Documents {
  documents {
    data {
      ...DocumentEntity
    }
  }
}

query DocumentBySlug($slug: String!) {
  documents(filters: { slug: { eq: $slug } }) {
    data {
      ...DocumentEntity
    }
  }
}
