fragment DocumentSlugEntity on DocumentEntity {
  __typename
  id
  attributes {
    slug
    title
  }
}

fragment DocumentEntity on DocumentEntity {
  ...DocumentSlugEntity
  attributes {
    title
    slug
    publishedAt
    identificationNumber
    supplier
    priceWithoutTax
    documentCategory {
      data {
        ...DocumentCategoryEntity
      }
    }
    files {
      ...FileItem
    }
    description
  }
}

query Documents {
  documents {
    data {
      ...DocumentEntity
    }
  }
}

query DocumentBySlug($slug: String!) {
  documents(filters: { slug: { eq: $slug } }) {
    data {
      ...DocumentEntity
    }
  }
}
