fragment FaqEntity on FaqEntity {
  id
  attributes {
    title
    content
    faqCategory {
      data {
        ...FaqCategoryEntity
      }
    }
  }
}

query Faqs($locale: I18NLocaleCode!) {
  faqs(locale: $locale) {
    data {
      ...FaqEntity
    }
  }
}
