fragment SlideItem on ComponentItemsSlide {
  title
  text
  media {
    data {
      ...UploadImageEntity
    }
  }
  backgroundColor
}

fragment HeroMainTile on ComponentItemsHeroMainTile {
  text
  link {
    ...Link
  }
}

fragment HeroSmallTile on ComponentItemsHeroSmallTile {
  icon
  link {
    ...Link
  }
}

fragment HomepageServiceTile on ComponentItemsHomepageServiceTile {
  title
  text
  link {
    ...Link
  }
}

fragment HeroHomepageSection on ComponentSectionsHeroHomepageSection {
  slides {
    ...SlideItem
  }
  mainTiles {
    ...HeroMainTile
  }
  smallTiles {
    ...HeroSmallTile
  }
}

fragment ArticlesHomepageSection on ComponentSectionsArticlesHomepageSection {
  title
  text
  articles {
    data {
      ...ArticleEntity
    }
  }
  showMoreLink {
    ...Link
  }
}

fragment HomepageEntity on HomepageEntity {
  id
  attributes {
    heroSection {
      ...HeroHomepageSection
    }
    articlesSection {
      ...ArticlesHomepageSection
    }
    koloSection {
      title
      text
      mainCards {
        ...Link
      }
      branchesTitle
      branches {
        data {
          ...BranchEntity
        }
      }
      showMoreLink {
        ...Link
      }
    }
    servicesSection {
      title
      text
      tiles {
        ...HomepageServiceTile
      }
      showMoreLink {
        ...Link
      }
    }
  }
}

query Homepage($locale: I18NLocaleCode!) {
  homepage(locale: $locale) {
    data {
      ...HomepageEntity
    }
  }
}
