fragment MenuLink on ComponentMenuMenuLink {
  id
  label
  url
  page {
    data {
      ...PageSlugEntity
    }
  }
  branch {
    data {
      ...BranchEntity
    }
  }
  workshop {
    data {
      ...WorkshopSlugEntity
    }
  }
}

fragment MenuSection on ComponentMenuMenuSection {
  id
  label
  colSpan
  multicolumnBehaviour
  links {
    ...MenuLink
  }
  hasDividers
  specialSectionType
}

fragment MenuItem on ComponentMenuMenuItem {
  id
  label
  sections {
    ...MenuSection
  }
  seeAllLink {
    ...Link
  }
}

fragment MenuHeader on ComponentItemsMenuHeader {
  id
  contactsLink {
    ...Link
  }
}

fragment Menu on Menu {
  menuItems {
    ...MenuItem
  }
  menuHeader {
    ...MenuHeader
  }
}

fragment MenuEntity on MenuEntity {
  attributes {
    ...Menu
  }
}
