fragment OpeningHoursItem on ComponentItemsOpeningHoursItem {
  label
  value
}

fragment OpeningTimeEntity on OpeningTimeEntity {
  id
  attributes {
    openingHours {
      ...OpeningHoursItem
    }
  }
}
