fragment PageEntity on PageEntity {
  id
  attributes {
    title
    slug
    perex
    header {
      ...HeaderSections
    }
  }
}

query Pages {
  pages {
    data {
      ...PageEntity
    }
  }
}

query PageBySlug($slug: String!) {
  pages(filters: { slug: { eq: $slug } }) {
    data {
      ...PageEntity
    }
  }
}
