fragment ParentPage on Page {
  slug
  title
}

fragment PageParentPages on PageEntity {
  attributes {
    ...ParentPage
    parentPage {
      data {
        attributes {
          ...ParentPage
          parentPage {
            data {
              attributes {
                ...ParentPage
                parentPage {
                  data {
                    attributes {
                      ...ParentPage
                      parentPage {
                        data {
                          attributes {
                            ...ParentPage
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment PageSlugEntity on PageEntity {
  __typename
  id
  attributes {
    title
    slug
  }
}

fragment PageEntity on PageEntity {
  ...PageSlugEntity
  attributes {
    perex
    header {
      ...HeaderSections
    }
    sections {
      ...PageSections
    }
  }
  ...PageParentPages
}

query Pages {
  pages {
    data {
      ...PageEntity
    }
  }
}

query PageBySlug($slug: String!) {
  pages(filters: { slug: { eq: $slug } }) {
    data {
      ...PageEntity
    }
  }
}
