fragment ChildPage on Page {
  title
  slug
}

fragment PageChildPagesEntity on PageEntity {
  __typename
  id
  attributes {
    ...ChildPage
    childPages {
      data {
        __typename
        id
        attributes {
          ...ChildPage
          childPages {
            data {
              __typename
              id
              attributes {
                ...ChildPage
                childPages {
                  data {
                    __typename
                    id
                    attributes {
                      ...ChildPage
                      childPages {
                        data {
                          __typename
                          id
                          attributes {
                            ...ChildPage
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment PageSlugEntity on PageEntity {
  __typename
  id
  attributes {
    title
    slug
  }
}

fragment PageCardEntity on PageEntity {
  ...PageSlugEntity
  attributes {
    updatedAt
  }
}

fragment PageEntity on PageEntity {
  ...PageCardEntity
  attributes {
    perex
    alias
    header {
      ...HeaderSections
    }
    sections {
      ...PageSections
    }
    sidebar {
      ...PageSidebars
    }
    seo {
      ...Seo
    }
  }
}

query Pages($locale: I18NLocaleCode!) {
  pages(locale: $locale) {
    data {
      ...PageEntity
    }
  }
}

query PageById($id: ID!, $locale: I18NLocaleCode!) {
  page(id: $id, locale: $locale) {
    data {
      ...PageSlugEntity
    }
  }
}

query PageBySlug($slug: String!, $locale: I18NLocaleCode!) {
  pages(filters: { slug: { eq: $slug } }, locale: $locale) {
    data {
      ...PageEntity
    }
  }
}

query PageRedirectByAlias($alias: String!, $locale: I18NLocaleCode!) {
  pages(filters: { alias: { eq: $alias } }, locale: $locale) {
    data {
      ...PageSlugEntity
    }
  }
  articles(filters: { alias: { eq: $alias } }, locale: $locale) {
    data {
      ...ArticleSlugEntity
    }
  }
}
