fragment ServiceSlugEntity on ServiceEntity {
  __typename
  id
  attributes {
    title
    slug
  }
}

fragment ServiceSections on ServiceSectionsDynamicZone {
  __typename

  ... on ComponentSectionsCardsList {
    ...CardsListSection
  }

  ... on ComponentSectionsDocuments {
    ...DocumentsSection
  }

  ... on ComponentSectionsFaq {
    ...FaqSection
  }

  ... on ComponentSectionsRichtext {
    ...RichtextSection
  }

  ... on ComponentSectionsFormCtaBanner {
    ...FormCtaBannerSection
  }
}

fragment ServiceEntity on ServiceEntity {
  ...ServiceSlugEntity
  attributes {
    serviceCategories {
      data {
        ...ServiceCategoryEntity
      }
    }
    image {
      data {
        ...UploadImageEntity
      }
    }
    sections {
      ...ServiceSections
    }
  }
}

query Services($locale: I18NLocaleCode!) {
  services(locale: $locale) {
    data {
      ...ServiceEntity
    }
  }
}

query ServiceBySlug($slug: String!, $locale: I18NLocaleCode!) {
  services(filters: { slug: { eq: $slug } }, locale: $locale) {
    data {
      ...ServiceEntity
    }
  }
}
