fragment ServiceSlugEntity on ServiceEntity {
  __typename
  id
  attributes {
    title
    slug
  }
}

fragment ServiceSections on ServiceSectionsDynamicZone {
  __typename

  ... on ComponentSectionsCardsList {
    ...CardsListSection
  }

  ... on ComponentSectionsDocuments {
    ...DocumentsSection
  }

  ... on ComponentSectionsWasteRemovalCards {
    ...WasteRemovalCardsSection
  }

  ... on ComponentSectionsFaq {
    ...FaqSection
  }

  ... on ComponentSectionsRichtext {
    ...RichtextSection
  }

  ... on ComponentSectionsFormCtaBanner {
    ...FormCtaBannerSection
  }
}

fragment ServiceCardEntity on ServiceEntity {
  ...ServiceSlugEntity
  attributes {
    serviceCategories {
      data {
        ...ServiceCategoryEntity
      }
    }
    image {
      data {
        ...UploadImageEntity
      }
    }
    seo {
      ...Seo
    }
  }
}

fragment ServiceSearchEntity on ServiceEntity {
  ...ServiceCardEntity
  attributes {
    publishedAt
    updatedAt
  }
}

fragment ServiceEntity on ServiceEntity {
  ...ServiceCardEntity
  attributes {
    serviceCategories {
      data {
        ...ServiceCategoryEntity
      }
    }
    image {
      data {
        ...UploadImageEntity
      }
    }
    sections {
      ...ServiceSections
    }
  }
}

query Services($locale: I18NLocaleCode!) {
  services(locale: $locale, pagination: { limit: -1 }) {
    data {
      ...ServiceEntity
    }
  }
}

query ServicesStaticPaths {
  services(pagination: { limit: -1 }) {
    data {
      ...ServiceSlugEntity
    }
  }
}

query ServiceById($id: ID!, $locale: I18NLocaleCode!) {
  service(id: $id, locale: $locale) {
    data {
      ...ServiceSlugEntity
    }
  }
}

query ServiceBySlug($slug: String!, $locale: I18NLocaleCode!) {
  services(filters: { slug: { eq: $slug } }, locale: $locale) {
    data {
      ...ServiceEntity
    }
  }
}
