fragment TagEntity on TagEntity {
  id
  attributes {
    title
    slug
  }
}


query Tags {
  tags {
    data {
      ...TagEntity
    }
  }
}

query TagBySlug($slug: String!) {
  tags(filters: { slug: { eq: $slug } }) {
    data {
      ...TagEntity
    }
  }
}
