fragment WorkshopDateItem on ComponentItemsWorkshopDate {
  datetime
}

fragment WorkshopSlugEntity on WorkshopEntity {
  __typename
  id
  attributes {
    title
    slug
    dates {
      ...WorkshopDateItem
    }
  }
}

fragment WorkshopEntity on WorkshopEntity {
  ...WorkshopSlugEntity
  attributes {
    sections {
      ...PageSections
    }
  }
}

query Workshops {
  workshops {
    data {
      ...WorkshopEntity
    }
  }
}

query WorkshopsStaticPaths {
  workshops(pagination: { limit: -1 }) {
    data {
      ...WorkshopSlugEntity
    }
  }
}

query WorkshopBySlug($slug: String!) {
  workshops(filters: { slug: { eq: $slug } }) {
    data {
      ...WorkshopEntity
    }
  }
}
