fragment WorkshopSlugEntity on WorkshopEntity {
    __typename
    id
    attributes {
        title
        slug
        dates {
            datetime
        }
    }
}

fragment WorkshopEntity on WorkshopEntity {
    ...WorkshopSlugEntity
    attributes {
        sections {
            ...PageSections
        }
    }
}

query Workshops {
    workshops {
        data {
            ...WorkshopEntity
        }
    }
}

query WorkshopBySlug($slug: String!) {
    workshops(filters: { slug: { eq: $slug } }) {
        data {
            ...WorkshopEntity
        }
    }
}
