/* tslint:disable */
/* eslint-disable */
/**
 * ATS API (Nalgoo)
 * Import and export REST API for Nalgoo\'s ATS
 *
 * The version of the OpenAPI document: 0.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common'
import type { RequestArgs } from './base'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base'

/**
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
  /**
   * Status of operation, will be \"error\"
   * @type {string}
   * @memberof ErrorResponse
   */
  status: string
  /**
   * Operation status code, see HTTP status codes (4xx - client error, 5xx - server error)
   * @type {number}
   * @memberof ErrorResponse
   */
  code: number
  /**
   * Error message
   * @type {string}
   * @memberof ErrorResponse
   */
  message: string
}
/**
 *
 * @export
 * @interface ExtendedErrorResponse
 */
export interface ExtendedErrorResponse {
  /**
   * Status of operation, will be \"error\"
   * @type {string}
   * @memberof ExtendedErrorResponse
   */
  status: string
  /**
   * Operation status code, see HTTP status codes (4xx - client error, 5xx - server error)
   * @type {number}
   * @memberof ExtendedErrorResponse
   */
  code: number
  /**
   * Error message
   * @type {string}
   * @memberof ExtendedErrorResponse
   */
  message: string
  /**
   * List of fields with error (if applicable)
   * @type {Array<string>}
   * @memberof ExtendedErrorResponse
   */
  fields: Array<string>
}
