apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBYGgwrqYGhZi8Yf8UavS/ufVoBLNUp69w9So3s7B39PpyDt4/y+sLOTAaHYMk0rSzLz8QvxNFgh2y3H/T+6KaMGnhA7Vssrd9txCt9SA8zoIIUEBP8C3ULcIb83SsPWqFwk+u7kYyHSCt5M5PMZGFD+O9N7PJ3bR4L2pYj4z/Ip/E375kjHN8zdH8NFu2oNSL58ETYvRYpw9OzXSSzHYMeChxvLAGdTIqU+rbKrqRANNXV9Blfan8es71pS+suuY81I4bumF2eJhgLYtA+4EeN6Nd8r7n2JnZH2ZJ0HCuxc8hEOpdqkZzMB24zAuPfSNLZhtAE2qgWpAfk40UZXWItMb8ePtOzybxfTgLYgbmfhwxPT/S153M41hOefPj2obqVPR/Mq49coILEygaaW/lpB/QWvPw/Y49nYMQa1l2I7fcx8LNGmjrkC+QU62X6c7T3jl5lrK0+An6kRKkCEeG5h0DHuH4tFDrLHkGkoQbAKnp1zzRCNataIHmN7HmWVq0oiLzVoWSVkAi/yAcK0xgpMAk+DZh1DfnE8Nr9b/l7+oVSyxtyDYTSlhHDB00BFF5e1l1K516riw7zbgFifkZAfniSNJWIVLClK7sX4ue101GVLQ/F/yyxav7ft8xtIrAclYuMDrpDWBt/Fh1ZCw0YzZvHTfiLk+CO0M5f36+bPJbDBeM/jT9aQLXjoLmx0L8P3us2ykS+Zurh+sY/YWthENIHBjq29kA=
    POSTGRES_PASSWORD: AgCX3f1mx4NVJQE9AEnP15fD7GQF91Pw/t8MrVi5yTTh49HktgiJWEpLMKSIlRVmrTaQNzoagrOZFKYv7aHZ4IFlcKV7uLYg9ATFVLS4pvsepocLuJclbVvC1Q/N2OHqMCwmruLBeXi++578MT37XF+nRF7n3usNLabkNXvkOvIxT2ZFFj4F9/XWqpBrpYHf862PN5UB5OZnXPLEL1Vrc5t0rzOlEJpMl3ctaJ0KFVIaETrAVr+4ka2SqK/R4k8OqeVbEP2iuA6kCMBpeUw1VgDnHVkRU+3v+jiY+mwx56ibDYxuugG6an84XbcXRoxOhP8SE/0fDeh7MuleLWUng2k96u2K1+Cr+tFGTeYWYrsZGt77v6ko+c2lYoKBkkvDjMiu4n7gAmfn5bAQbb88S4zmdlVv5AhzjVRC7W5qYZGhSBqgL3wBYOnjUfyEq+puYEtbkASZ225p2/030nbqLosc9WxZEzxaL7PdwKLcgOLsod6E/Idd2tqWQoqGDg6JGMO9Xt9QYioA1+vTdoNv0GLF5DF0N6zqd8EI9BzVR1V60Uax/zop1GAOpteIP7b5ptPKB/7mkr99YTq7oD7AA9GgLz8p99YpJFFq72zwrS7kwRPoaBKBU2sG7uhFwef7jt3IBNlYkcAgBftF+Gz/Pyi0kxgwA9aJ6P/Rt6DWGOPL8OhPeiEHFaQFFdum8XgfS3NuDtFzfXME6L2hajHSVUhd011Z+gWPqeo=
  template:
    data:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: "${BUILD_REPOSITORY_NAME}"
        source: "${BUILD_REPOSITORY_NAME}"
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: "${NAMESPACE}"
