apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgAJEogvjqzXdeonwKSDsuYEgrgA6Rp0eqKjAMAP/Lg+NYmSI5iVli3yq8LqJloCXI/+bklHLB6AZkvbfvcJ37Y/Mu3xw/w378T8a2otM88RqoXhosLvkN3h+5/uG33RxEo0kcW2Y3RUsRPBi36onKBhbfjXtwxkPWgxxgXocq1ZDt5pOarbTzOnTwqmukLpVksDWqA95lTXaMxWaJsNSYTlGmRczHjU4g6IGt3iLXonc8re+uW8wWbk4pSyF1FxfVyrgeqFxiap9FlYjgNRcVS9kJiwPAhBUARjKbnhpkWoL9fcabHhRmeYlvJzEv7l0WP7Iht8sNKAiG4MxtxqiCdtj0X9nfIOHxHri8xsvfWqAVV0K88G3W243ISq1BFERmWAjTbxAbYmJ/DO6oOrBa4s2R4wG5mVoT0LuuuR3sz03mm1BDb4kcO6pg+ub8YLvI25nLaxtXmSdVxkjTs/QpZaD8U2qey/EmYdtL/Lw3g0ma5HPOJraYxCHHPMsNp6STHwsHLmDzXKO2348KLuH5BL29K6jYmw52ccdVmcfD5B0qx5xmqcObn8Vs+/TbV2tmMMb/Iu6P/X6MUxBbC5Dzx890TcjdoWG+lHxt+uxbnHcPuc39irNciGHG6pTD0J7pBrh4JcsO3lKUn/qQ/iB6OAEui8GYD0l65vDLQpdCPl3E+LA4FBVbDwbxMvkPZCllP2bm2CCKf7m32mDEr4gep5LWqhBmukYesnPWI+2C0XP2bwjFxtvzDx6Ug56flej2/CZqtjkbe0m7Uvs0OwxTc=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
      namespace: ${NAMESPACE}
