apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgCnBgZtyx9+kcvNaquMJt/qqBiTnrPT/o5ZWUT3NW+WuVU84xF9cookxtf9qX88vefA6jY7t1wm5VdAcmo0fL4ezTLvK4ERmGGPkD7pgVdjItnD0UjKXJFdLXQOp3HkJzhSYq6NQxAjuRhW3+2uy0zrlsBZAII125pkGsu1X5gJwJYCdxn/4OZg8hWao1csemPrwRmf/HPNob41Js0yX3+FRJOJmKB/mi/JOCv6AIDehTornEYKiXTSTuxmCkXOIMoMyt7CUyOOaCS7wl3DDOyHOTw0O+5inkI5gA9R61WGCQwFjHwbwwDc9p8h96+s+/ZSFeowNKqAl7onHRSipxPIpEXU6gewpggHb9I4EECOExtwWBaWFnMlQ+IFcNoO4qW1PCp9hF8EAJdik0iytlKfu98N7GxoRxKL9zcgE/a6cT6iv+W2UYDNqxo4WKvk4TPZF3gHZNAubWqlcTaFEkzvgxgwP5m/rt+ZkArg2Zwl9pGqNPp1phIazNeQrUcGXcvvSA4NjuYy8KHvow7yZQJOkfFqh7eSiQk8WMmpcnbDk+PzLyW1kx9RdEcYwRb93Yj2TTXDu74WESJdMesE+Je5bBj/Wz4LBKxQvgPyGIEQx8lD0jEk1wZ5xpTfVoAgUM2Y0RX34XAjws3aTbD9mpSENJsTsyEtrACCWTKDeJf8onR4ZcMDtYMbgMKPUGs2U6ZNr+Au0F4xNpqil+IstjxVx+osaGzb7xMp5KkQzjC57uCvSSnNtfCyZ/d5x8w7WWu1FFBBgfJAP8HwS3MLqYk=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
      namespace: ${NAMESPACE}
