apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBnyl7VhBUPG8e4Xsd3RKMQhT1wwGO4OTHixG+TooYfCWY2KDR6Gy0k/vkTo/dud5tADUtc1sqv8rnH8VjecfxcS4U9U2CxSLkHoE7/ywl6pU0U8NY5h9lj84kBPA9Z9F0kqQhNmsij0zeTkwgJRe6WlTa/WMFQ+3+vcWmMLXLWWlJtEdHCOvFoJy+lZkGVUpgUYqcIfQXqSXzScdY0c1HevJlQa/+8+qCabh4Qqsgl6b3I958CdccGhpfORrcWDVG219g+YYtrIzHI2KeWJFHROoHG0//cedx51aZ3wDD6BAEMw8ZHlYpJ1tSRSHgmifbHe6HFNQiaa0NGZFffkm8W2X/wwES07xxKeUbnOZJ7kgraKN4mtmGF866hlK/MR7Tj3275UuYfmKzzoRcNrkTChs5uD4mSUTuO7VbQIu48VQiSLCFHDNHtGIdqMFQXb2zcYEpgolrayFflWu3F6ClZH1achoUeufABLvv5su7g12siuJJa2iwBK0QjYmeFkEIUH3oeCCE1FtMguQHjC6U9LzypFVhnxYbuU1yhl5qLB60nosclpZzk5B7aW3mDoM/LaDw4tlFHL2+pRGHc5efpZPVno+qWbT9SLGOmGn+ImSNGXdE6g65+S5TFFk75hUr72354tJDEhB2SAgeYP5MAflk3Fi1EU5g/PGX3eyWlZvzUeHvnURcq5mWZVSXvXAzKR4PeGtRto4XXcweioC2Pd+uOGg3C/k9B2pBA3iSF0CqgqHgxSJnxW9niWTqS2X2fkwQINQMRZHZdPLI6mBY=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
      namespace: ${NAMESPACE}
