resources:
  - deployment.yml
  - service-app.yml
  - ingress.yml
  - service-storybook.yml
  - storybook-nginx-conf.yml
  - stateful-set-meilisearch.yml
  - service-meilisearch.yml
configurations:
  - configuration.yml

# Keep as is
#namePrefix: ${BUILD_REPOSITORY_NAME}-
commonLabels:
  app: ${BUILD_REPOSITORY_NAME}
  source: ${BUILD_REPOSITORY_NAME}

commonAnnotations:
  repositoryUrl: ${BUILD_REPOSITORY_URI}
  commit: ${COMMIT}
  tag: ${TAG}
  image: ${IMAGE}

configMapGenerator:
  - name: ${BUILD_REPOSITORY_NAME}-env
    namespace: ${NAMESPACE}
    envs:
      - .env
  - name: ${BUILD_REPOSITORY_NAME}-meilisearch
    namespace: ${NAMESPACE}
    envs:
      - .meilisearch.env
