apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    DATABASE_PASSWORD: AgADAh1OFjWoj1i6ctEGqBzwP5x+/7LMn959wwTHGEqav1du/QwErVN0ydvXYR761NCczxn07WVfrzz0n8aMsQb1I4tXHoO31tuxLnozNGkjkIz8Op7rj+QvyYALrVqlEdDi+GurnrxnJWnnMolJTQAx1DWAHDC+jpjlEuvsL0tftG5ktUWUSJ+PZSE4z23z5WdhAiEmX0PT1Mp/YXJxfolJDdT/bq+kC2HCPM/W2SuHGMWl45tpgnHYxkHgovZCRVRmObcSnS80Rv1jGmN+e+RB8nEGCC7+8YiuEabnQStiimbpVjuH5vBYuttuuvRtpM89xgxNX09mwpBmMxGQllwYQCjrAcW2H7YWOAHKZzTSGqTuuVOQ7UnEEjKHZoUhx/ODgM0gLBAk8WXyjJ+xwAtMUd0V/MuG55YU64ErlQS0FvHKKfIc7+qA6R/963rHw2tUiNq9FDZPRhvbSX9LS807Zk6ZwVPiCBN1G3L6Bqnr3euSOVuUjCILHyKyzcLSPuYVf/82wLT4UAuEhFbEdTL0NBxhC8ZMpA1D3LYSQ4NhzvM/BZsFQkXQAZMwUS5/wffoUprof+ploHQn1i494BBS4o2Jk+VVej6Rs81eSmUXMJ6/57DyiRaavU6ZNb1WkiKcB4Xp9GGlIlet/n02WteOLFafCRZQB6SUO60oQjRGMEsi65qKbVGWjQFZOt8NnmzkgRMnhc+fZKMos+cCo7V1V93LEeUXBL4=
    POSTGRES_PASSWORD: AgB4ubjD1AS1x5E2gurnGH1ubI/OglEtcWmVBZHHNcD5Gl/ojPS+DaZTjh20Bo3oSqzaYPMUx83VTHhA0j9l8MnBBZYiZPMgJqSbmAyNQC9/Nz1OuTyin0zstRkdzqecMTfbgAgULpB/RG5Hy5W7baDIJWjnGThztXxxfy3sowysPAOMhMvgAuAEL2EvZYBIf8MX5yMHZs93ZzxZBau14+u01JhfBAgK6PVbn6jWvtDPx7uHfkx3YNGlwsBtVlQ+Sw5NbcpmHInOovaQnqggtkNY4SyW2dxJgDlhXLwsXdtxS709SS3puztVkP7XJ17VbsZWxVZu+hAyjkh+FR5HA1JGN57ZGWJXy6Fkeyq5Y/wirDc+3Op1kGzj0r2qli9zuXsuSvo95j0DoIQAOUOq2XqUyC5ZDCTHBY3PHrPdRfsrF5YLlE38K78pp8SQOSdTTVZ7j/Y1LXBp8dbsXzCL4mMd4OdWc/LohpMcdizOglK5OveNnxh6X0KoTch/inchB94XRPHbCpkGPJ/rUBlUlo62RcjiJf0hZtfecSUjVyRp4BcmDdCqtZfha0DbyPl84PzsUbhgVFENzpFWQr1aHWJEt0FRdITxiFoo0hmewLfiADhWkdagj3Un6v1ZwW4tggBV+7OnZ31X0Qjma99a+rA6aq4Y4L/0IcMCMqVBHQ7aDaa6hQhHOtu1Zoq8KD1Yf2bCe71slpks+VccMPgPsd8B2D0ZV+Oavik=
  template:
    data:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: "${BUILD_REPOSITORY_NAME}"
        source: "${BUILD_REPOSITORY_NAME}"
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: "${NAMESPACE}"
