apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    DATABASE_PASSWORD: AgC568RoAPPSPytlviHPnFX8kTefWwN4tMcu9FUkzQm/07Zjt/HOY1tFDJ+8QbqEW+e4e9kgJJhaCP8kxB4hxZjkwhwI3ib2Xe7SralMid1Vxr9bGLMIV1j8Gb1jRMcEvAWu7ZQBM9edoPJfBJaOIIcVTXSva6a/yeX49ODqZ9NFQY+jklUemaG5apvL07BVrTg7RnwwxZYlL5sDqYro+DKBA+MIesxkGIJPjLvxG7L7/xrc/ot95XacTJWP+NS/yKn4YWHpfmr80YLTO4cx5JZ7pCCDhlCKpStGub7+cf5QEN7N7qLWWgXnBsarKs5kycAMdktoKKZnwMs7NBGQgu1xILi+SHrSvSnEkTXnUqwlPPSa6nbnUwS+G5D9rKI6MrBNwNBZGoDmMP8h5twqi5yRgj94GpXYQneARfOwDijH1Sf+zOITjeQIQF405EbM3ulZW27GPtICV/ICVsLONULR9aeDm13/4K29SrgGUFC5iShZLXU8unlCvJAUG/CPOc7z08keNYKYcUuLAlMPnaHDtbuynr289jb60gH6/Rb8sGMShD3McbkECdPpMgUQvBVm1om6ZOlOAmLYyGe2EfyhnNZsqpvRrrlrK19JDa1c3HBPoOkbKtyjhMqrsKNTzR0qcO+ZbTBHIGkE2agkeN5OIt9c7Vd2fCEU/YIXrZ7qaoPLe4JEQnZLid4eU2CRXgQtRgiV5CwjOb1BEIeYMq1qh9mKqmBmjS8=
    POSTGRES_PASSWORD: AgDEYN1nslpZIXwvXsM5eML9z4HPWHXve5untv/43vMQgrMTU9A2VdPvOcNRKgvGt9mrkdxg46GHy8xDmY30kiIaWUj4rjeXT9jHfmp7N60gnAhOCLMAN3cANdGB5czsH907BQb39UMa5jy/8gpatTYj3tp8qfLpuRY19N0jq12tZxETcxn5J3ivXb11NsE8BiIO8+6JG9JoJM4Rmap6z23dE28zKrkmctVYAYe/v8U3mpD6x53S4kYWIzVv/62wqESvZ7hCWQkL7qfIedxhfNn6KB1HEX/YEVRfvtgssLqRnPiGfVEpJpSCVd982kQ2nWUFRq67WjBe66/zQlF1BZEJVkuNYZr+9EZLdlvBsZo3QWqDuXEDI3CJiOHsCqxR9IghDQ+9Tu2BiBtwbRcXNwA7erCr2Xe7HRuQ5RrDPw80mUXnPSO3u4z2owr7LDAIUDpu3TsaFCIFm4RPNoO0/7O7JuVw941CIBy6IfrACtLPmePJAXKgQ4u20vrP82QL2bdZBAlsZMYoUy/iq39E1+6Rc5hOyUNmlFuzBTLR0dcQ/pyyIv/+QSJTYTfPbm7RQ5OjqxnlL4/flHxnuqWt53jn+kjzzwwz6wOKasHTaioqAP87LtM/e2hyfoGG9OIGLzevNeLNKsGBl6FnNYzOi3xM3RmYcNOx+dRQR6XGLG/V7sq+7gb8cryHMHsdMburq2lW7mMcuTOA/NvJXBVCJixoaQDKMeARgag=
  template:
    data: 
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: "${BUILD_REPOSITORY_NAME}"
        source: "${BUILD_REPOSITORY_NAME}"
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: "${NAMESPACE}"
