apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgA1I6YiHXGyoRDFwwlyUsgVkMsLGAqZWZPWjeZaSIsGl9DzX4nsK5MxTwyLgGwqX1cMpjwsYPX2MtsxryzoRVgmISFO3fjWfO2aZhZ4QvC/Q5KHHyBE4Rq3ya0W/iMpSM4pc6PqrENAt9bBxklZSJh+NkVcPnobhBh4WWwwp3OEzb6FINTy65rMQA37TsFTaqTM/lFob7lUIb/t8LBgUyNNHfJfytkAYaitwbNVXZbrrLU0l3q3BFVLao7pnxkW0b1WMKPF9JPTJwL6Nlhla9dDHVXYGgusB03zvMCqEknw5IwqUkwEp/DfbS4sIQYfxgcYejN90paz+LThRbTnNtHPCUfZd2xH/QefUUODZXZ4RrKRWv/4bYM2psikOYbwFoHgnd1vI1ttoxfIjWJ6r/94WbfeUil7wzOMLcSDhAWtG+AI7ozhU3nfae0je1qIH7FvXNPqUeezgHDgWjBePblBlKWbcxzRSHEMIO081K+z/q6gnkwd0j3E30a2EGVEGhBW9X1Ng5sxolxE37brOmMSbF+oeoRRO6ezvorS0zBS9HUbCtTI0xFlWu69/hxrWHN4A2dXjzM8qVCZ0tsONeRo8QgUG2+z34Ng+2rsJmqVHFY0E3aPHWeMXywU/u/HXq9MtDGiW1LRElhgIehgo76SHHXwF6A7vNBO9kh6kXB/ah5/7Icoymw2bDveIxjdes2pwgucBkH8jsr9dY9JtAZAWy50VnBsVYJ9IOGrFUbgzfG35qUzfj2/Mskn9BfTnTxVLWFxeSvgQP7ftFjBvbM=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
      namespace: ${NAMESPACE}
