name: Validate
on:
  pull_request:
    branches:
      - master
jobs:
  validate:
    name: Validate typescript
    uses: bratislava/github-actions/.github/workflows/validate-typescript.yml@beta
    with:
      directory: '/next'
